### ISSUE TITLE
Is there any info about the pin mapping?

### ISSUE THREAD

**Issue by IdontKnowWhatToNameThisAccount** [rhalkyard/plotadapter#1]
Im not sure if im missing something, but I cant find any info about the mappings of arduino pin --> gpib pin. Could you perhaps add them?

**Comment by rhalkyard** [comment]
Assignment of Arduino pins to GPIB lines is done in config.h (along with various other options).

**Comment by IdontKnowWhatToNameThisAccount** [comment]
I've already seen that file, but I dont really understand what the pin mappings should be, sorry for causing further trouble. My main problem is that I dont see any numbers that are obviously arduino pin refrences, I would expect to see at least one or two analog pin refrences, easily spotted because of the "A". Do you mean the area between the lines 31-47? I suspect thats what it is, but the big numbers used there dont correspond to any arduino pins from my rahter limited knowledge. Again, sorry for bothering you further.

**Comment by rhalkyard** [comment]
That's correct, lines 31-47 of config.h are the pin mapping. The default pin numbers are so large because I used an Arduino Mega2560, which has a lot more I/O pins than a regular Arduino Uno, and the physical layout of the Mega2560 made those pins especially convenient for the cable I made up.

In theory it should work on an Uno too, but you will need to change those pin numbers to something suitable - I'd suggest 2-13 and A0-A3. Pins 0 and 1 are used by the serial port, so those shouldn't be used for GPIB pins.

Sorry it's not a particularly intuitive or well-documented codebase; I threw it together on a snowed-in weekend to get my HP 7470A working and haven't really looked at it much since.
